In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.utils import shuffle
import pickle

colnames=['flow_packet_count','flow_byte_count','rx_packets','tx_packets','rx_bytes','tx_bytes','Label']
target_name="Label"

df=pd.read_csv("demo.csv", names=colnames)
df = df.iloc[1:]
if list(df.columns.values).count(target_name) != 1: 
    print("No target Label Found!")
    


print(df)
columnsToEncode = list(df.select_dtypes(include=['category', 'object']))  
le = preprocessing.LabelEncoder()
for feature in columnsToEncode:
    try:
        df[feature]=df[feature].astype(str)
        df[feature] = le.fit_transform(df[feature])
    except Exception as e:
        print ('error:'+ feature)

target2idx = {target: idx for idx, target in enumerate(sorted(list(set(df[target_name].values))))}
X = df.drop([target_name], axis=1).values
X = (X - X.mean(axis=0)) / X.std(axis=0)
y = np.vectorize(lambda x: target2idx[x])(df[target_name].values)
n_classes = len(target2idx.keys())


file_name="models/save_file1.pkl"
with open(file_name, 'wb') as output:
    pickle.dump(X, output, pickle.HIGHEST_PROTOCOL)
print("uploaded")


N, d = X.shape
print(X)
print(y)

  flow_packet_count flow_byte_count rx_packets tx_packets rx_bytes tx_bytes  \
1               960         1384320        873         53  1257466    75044   
2              1736         2503312        869        259  1253098   373478   
3               757         1091594          0          0        0        0   
4               868         1251656          0          8        0     1032   
5               867         1250214        869        137  1253098   197554   

  Label  
1     1  
2     1  
3     0  
4     0  
5     1  
uploaded
[[ 1.41421356  0.70710678  1.60356745  0.70710678  1.60356745  1.41421356]
 [-1.41421356  1.41421356  0.26726124  0.          0.26726124  0.70710678]
 [-0.70710678 -1.41421356 -1.06904497 -1.41421356 -1.06904497 -1.41421356]
 [ 0.70710678  0.         -1.06904497  1.41421356 -1.06904497 -0.70710678]
 [ 0.         -0.70710678  0.26726124 -0.70710678  0.26726124  0.        ]]
[1 1 0 0 1]


In [8]:
import numpy as np
from src.NN import NeuralNet
import src.utils as utils

In [9]:
model = NeuralNet(input_dim=d, output_dim=n_classes,
               hidden_layers=[5], seed=1)

x=utils.loadNN(1)
model.setNetworkDetails(x)

ypred = model.predict(X)
print(ypred)

network uploaded
[1 1 0 0 1]
